config/routes.rb
Rails.application.routes.draw do

  resources :users, except: :destroy do
    resources :stories, except: :index do
      resources :pages
    end
  end

end

app/models/page.rb
class Page < ActiveRecord::Base
  belongs_to :story

  validates :content, presence: true
  validate :background_url_good

private

  def background_url_good
    unless FastImage.size("#{background}")
      errors.add(:background,' must be a valid url!')
    end
    if FastImage.size("#{background}")
      if FastImage.size("#{background}")[0] > 2000
        errors.add(:background,' cannot be more than 2000px wide')
      end
    end
  end

end

app/models/story.rb
class Story < ActiveRecord::Base
  has_many :pages, dependent: :destroy
  belongs_to :user

  validates :title, presence: true
  validates :title, uniqueness: true
  validate :max_synopsis_size

  private

  def max_synopsis_size
    if synopsis.length > 300
      errors.add(:synopsis,' must be less than 300 characters long!')
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :stories
  validates :name, presence: true
  validates :name, uniqueness: true
  validate :max_bio_size

  private

  def max_bio_size
      if bio.length > 300
        errors.add(:bio,' must be less than 300 characters long!')
      end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :find_page, only: [:show, :edit, :update, :destroy]
  before_action :find_user_story

  def index
    @pages = @story.pages
  end

  def new
    @page = Page.new
  end

  def create
    @page = Page.create(page_params)
    if @page.valid?
      @story.pages << @page
      set_page_num(@page)
      redirect_to user_story_page_path(@user, @story, @page)
    else
      @errors = @page.errors.full_messages
      flash[:errors] = @errors
      redirect_to new_user_story_page_path(@user, @story)
    end
  end

  def show
    @bg = @page.background
  end

  def edit
  end

  def update
    @page.update(page_params)
    if @page.valid?
      redirect_to user_story_page_path(@user,@story,@page)
    else
      @errors = @page.errors.full_messages
      flash[:errors] = @errors
      redirect_to edit_user_story_page_path(@user,@story,@page)
    end

  end

  def destroy
    @page.destroy
  end

  private

  def find_page
    @page = Page.find_by(id: params[:id])
  end

  def page_params
    params.require(:page).permit(:background, :content)
  end

  def set_page_num(pg)
    pg.page_number = pg.story.pages.count
    pg.save
  end

  def find_user_story
    @user = User.find_by(id: params[:user_id])
    @story = Story.find_by(id: params[:story_id])
  end

end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  before_action :find_story, only: [:show, :edit, :update, :destroy]
  before_action :find_user

  def new
    # @user = User.find_by(id: params[:user_id])
    @story = Story.new
    @story.user_id = @user.id
  end

  def create
    @story = Story.create(story_params)
    if @story.valid?
      @user.stories << @story
      redirect_to user_story_path(@user, @story)
    else
      @errors = @story.errors.full_messages
      flash[:errors] = @errors
      redirect_to new_user_story_path(@user)
    end
  end

  def show
    @bg = @story.background
    @first_page = @story.pages.find_by(page_number: 1)
  end

  def edit
  end

  def update
    @story.update(story_params)
    if @story.valid?
      redirect_to user_story_path(@user, @story)
    else
      @errors = @story.errors.full_messages
      flash[:errors] = @errors
      redirect_to edit_user_story_path(@user, @story)
    end
  end

  def destroy
    if @story.pages
      @story.pages.each do |p|
        p.destroy
      end
    end

    @story.destroy

    redirect_to user_path(@user)
  end

# ----------privacy please! --------#
  private

  def find_story
    @story = Story.find_by(id: params[:id])
  end

  def find_user
    @user = User.find_by(id: params[:user_id])
  end

  def story_params
    params.require(:story).permit(:title, :synopsis, :user_id, :background)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, only: [:show, :edit, :update]


  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    if @user.valid?
      redirect_to @user
    else
      @errors = @user.errors.full_messages
      flash[:errors] = @errors
      redirect_to new_user_path
    end
  end

  def show
  end

  def edit
  end

  def update
    @user.update(user_params)
    if @user.valid?
      redirect_to @user
    else
      @errors = @user.errors.full_messages
      flash[:errors] = @errors
      redirect_to edit_user_path
    end
  end

  private

  def find_user
    @user = User.find_by(id: params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :bio)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>QuillTreePrototype</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
</head>
<body>

<%= yield %>

<footer style="background:#3e3263; color:white; padding:0; min-height: 50px;">Back to <%= link_to "Writers", users_path, class:"link-to" %></footer>

</body>
</html>

app/views/pages/_form.erb
<!-- content background page number -->

<% if flash[:errors] %>
  <% flash[:errors].each do |e| %>
    <p style="color:red;">// <%= e %></p>
  <% end %>
<% end %>

<%= form_for @page, url: url do |f| %>

  <%= f.text_area :content, class: "lg-txt-field" %><br><br>

  <%= f.label "Link to a background image" %><br>
  <%= f.text_field :background, class: "url-field" %><br><br>

  <%= f.submit %><br><br>

<% end %>

app/views/pages/edit.erb
<%= render "form", url: user_story_page_path(@user, @story, @page) %>

app/views/pages/index.erb
<p><%= @story.title %> by <%= @user.name %></p>

<% if @pages.count > 0 %>

  <% @pages.each do |page| %>
    <p><%= link_to page.page_number, user_story_page_path(@user, @story, page) %></p>
  <% end %>

<% else %>

  <p>There are no pages yet!</p>

<% end %>

app/views/pages/new.erb
<% if @story.pages.count > 0 %>
  <p>Page #<%= @story.pages.count + 1 %></p>
<% else %>
  <p>Welcome to the first page of your story!</p>
<% end %>

<%= render "form", url: user_story_pages_path(@user, @story) %>

app/views/pages/show.erb
<!-- This will change the background to whatever you choose -->

<script type="text/javascript">
// Ooooh sexy jQuery :D
$(document).ready(function(){

  var bg = `\"${$('.bg-data').data('bground')}\"`;

  $(".main").css(
    "background-image", `url(${bg})`
  );

  $(".main").css("background-size", "cover")
});

</script>

<!-- Main Page Div -->
<div class="main">

<!-- invisible div that stores ruby info for javascript -->
<%= content_tag :div, class: "bg-data", data: {bground: @bg} do %>
<% end %>

<!-- Links to story and user -->
<p><%= link_to @story.title, user_story_path(@user, @story) %> by <%= link_to @user.name, user_path(@user) %></p>

<!-- The content -->
<p>Content: <%= @page.content %><br>
Background URL: <%= @page.background %><br>
Page # <%= @page.page_number %></p> <br>

<!-- Edit -->
<p><%= link_to "edit this page", edit_user_story_page_path(@user, @story, @page) %></p><br>

</div>

app/views/stories/_form.erb
<p style="float: right; clear: both">Current User: <%= @user.name %></p>

<% if flash[:errors] %>
  <% flash[:errors].each do |e| %>
    <p style="color: red" >// <%= e %></p>
  <% end %>
<% end %>


<%= form_for @story, url: url do |f| %>
  <%= f.label :title %><br>
  <%= f.text_field :title %><br><br>

  <%= f.label :synopsis %><br>
  <%= f.text_area :synopsis %><br><br>

  <%= f.label :background %><br>
  <%= f.text_field :background %>

  <%= f.submit %><br><br>

<% end %>

app/views/stories/edit.erb
<h3>Edit <%= @story.title %></h3>

<%= render 'form', url: user_story_path(@user, @story) %>

app/views/stories/new.erb
<h2>Is it time to write a new story ...?</h2>

<%= render "form", url: user_stories_path(@user)%>

app/views/stories/show.erb
<!-- This will change the background to whatever you choose -->

<script type="text/javascript">
// Ooooh sexy jQuery :D
$(document).ready(function(){

  var bg = `\"${$('.bg-data').data('bground')}\"`;

  $(".main").css(
    "background-image", `url(${bg})`
  );

  $(".main").css("background-size", "cover")
});

</script>

<!-- invisible div that stores ruby info for javascript -->

<div class="main">

<%= content_tag :div, class: "bg-data", data: {bground: @bg} do %>
<% end %>

<!-- and the rest -->


<div class="main">

<h2><%= @story.title %></h2>

<p>by <%= link_to @story.user.name, @story.user %></p>

<p><%= @story.synopsis %></p>

<!-- Link to the first page -->
<% if @first_page %>
  <p><%= link_to "Start reading!", user_story_page_path(@user, @story, @first_page) %></p>
<% end %>

<!-- Link to pages index -->
<p><%= link_to "Pages Index", user_story_pages_path(@user, @story) %></p>

<!-- Edit -->
<p style="font-size: 0.7em"><%= link_to "Edit", edit_user_story_path(@story.user, @story) %></p>

<!-- Delete -->
<p style="display: inline-block; border: solid red 2px; padding: 5px;"><%= link_to "Delete", user_story_path(@story.user, @story), method: :delete, data: { confirm: "Do you really want to burn this book?" } %></p><br>

</div>

app/views/users/_form.erb
<% if flash[:errors] %>
<% flash[:errors].each do |e| %>
  <p style="color:red;">// <%= e %></p>
<% end %>
<% end %>

<%= form_for @user do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %><br><br>
  <%= f.label :bio %><br>
  <%= f.text_area :bio %><br>
  <%= f.submit "Submit" %><br><br>

<% end %>

app/views/users/edit.erb
<h1>Edit Writer</h1>

<%= render "form" %>

app/views/users/index.erb
<!-- Changes the image once this has loaded -->
<!-- Added more for testing purposes than practical reasons -->
<script type="text/javascript">
$(document).ready(function(){
  $(".main").css(
    "background-image", "url('https://images.unsplash.com/photo-1539213492139-7b268eb93c82?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=d648ff5e44746dc58e4e5b12a26fb204&auto=format&fit=crop&w=1600&q=80')"
  )
})
</script>

<div class="main">

<h1 class="pg-hd">Users</h1>

<% @users.each do |user| %>
<div class="in-box" style="margin-bottom: 10px;">
  <h3><%= user.name %></h3>
  <p>Bio: <%= user.bio %></p>
  <% if user.stories.count > 0 %>



    <p>Stories:</p>
    <% user.stories.each do |s| %>
      <p><%= link_to s.title, user_story_path(user, s), class: "link-to" %></p>
    <% end %>
  <% end %>
  </div>
<% end %>

<br> <p style="color:white; display: inline-block; background-color:black; clear: both;">Background Photo by Paul Gilmore | Unsplash</p>

</div>

app/views/users/new.erb
<h1>New Writer</h1>

<%= render "form" %>

app/views/users/show.erb
<h1 style="border-top: solid black 4px; border-bottom: solid black 2px; display:inline-block;"><%= @user.name %></h1>

<p style="font-size: 0.7em; margin-top: 0"><%= link_to "Edit", edit_user_path %></p>

<p style="padding: 4px; border: solid black 2px; display: inline-block"><%= @user.bio %></p><br>

<p style="border-top: solid black 2px; border-bottom: solid black 1px; display:inline-block;">Stories</p><br>

<% @user.stories.each do |s| %>
<p style="display: inline-block"> <%= link_to s.title, user_story_path(@user, s) %> </p>
<% end %><br>

<p><%= link_to "New Story", new_user_story_path(@user) %></p>